[package]
name = "toy-rust-async-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2.0"
anyhow = "1.0.65"
futures = { version = "0.3", default-features = false }
